/**
 * ============================================================
 * ADDITIONAL EVM CHAINS - More EVM Compatible Networks
 * ============================================================
 * Extended list of EVM chains for 150+ total networks
 */

import { BlockchainDefinition, createEVMChain } from '../types';

export const ADDITIONAL_EVM_CHAINS: BlockchainDefinition[] = [
  // ============================================================
  // MAJOR L1/L2 EVMs
  // ============================================================
  createEVMChain({
    id: 'base',
    name: 'Base',
    symbol: 'ETH',
    aliases: ['base-mainnet', 'coinbase-l2'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#0052FF',
    icon: '🔵',
    chainId: 8453,
    mainnet: {
      name: 'Base Mainnet',
      rpcUrls: ['https://mainnet.base.org', 'https://base.llamarpc.com'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'BaseScan', url: 'https://basescan.org' }],
    website: 'https://base.org',
    coingeckoId: 'ethereum',
    isActive: true,
  }),

  createEVMChain({
    id: 'linea',
    name: 'Linea',
    symbol: 'ETH',
    aliases: ['linea-mainnet', 'consensys-l2'],
    category: 'layer2',
    consensus: 'zk',
    color: '#121212',
    icon: '◼️',
    chainId: 59144,
    mainnet: {
      name: 'Linea Mainnet',
      rpcUrls: ['https://rpc.linea.build'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'LineaScan', url: 'https://lineascan.build' }],
    website: 'https://linea.build',
    coingeckoId: 'ethereum',
    isActive: true,
  }),

  createEVMChain({
    id: 'scroll',
    name: 'Scroll',
    symbol: 'ETH',
    aliases: ['scroll-mainnet'],
    category: 'layer2',
    consensus: 'zk',
    color: '#FFEEDA',
    icon: '📜',
    chainId: 534352,
    mainnet: {
      name: 'Scroll Mainnet',
      rpcUrls: ['https://rpc.scroll.io'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'ScrollScan', url: 'https://scrollscan.com' }],
    website: 'https://scroll.io',
    coingeckoId: 'ethereum',
    isActive: true,
  }),

  createEVMChain({
    id: 'zksync',
    name: 'zkSync Era',
    symbol: 'ETH',
    aliases: ['zksync-era', 'zksync2'],
    category: 'layer2',
    consensus: 'zk',
    color: '#8C8DFC',
    icon: '⚡',
    chainId: 324,
    mainnet: {
      name: 'zkSync Era Mainnet',
      rpcUrls: ['https://mainnet.era.zksync.io'],
      defaultPorts: { rpc: 3050, p2p: 30303, ws: 3051 },
    },
    explorers: [{ name: 'zkSync Explorer', url: 'https://explorer.zksync.io' }],
    website: 'https://zksync.io',
    coingeckoId: 'ethereum',
    isActive: true,
  }),

  createEVMChain({
    id: 'mantle',
    name: 'Mantle',
    symbol: 'MNT',
    aliases: ['mantle-mainnet'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#000000',
    icon: '🏔️',
    chainId: 5000,
    mainnet: {
      name: 'Mantle Mainnet',
      rpcUrls: ['https://rpc.mantle.xyz'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Mantle Explorer', url: 'https://explorer.mantle.xyz' }],
    website: 'https://mantle.xyz',
    coingeckoId: 'mantle',
    isActive: true,
  }),

  createEVMChain({
    id: 'manta',
    name: 'Manta Pacific',
    symbol: 'ETH',
    aliases: ['manta-pacific'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#00B4D8',
    icon: '🦈',
    chainId: 169,
    mainnet: {
      name: 'Manta Pacific Mainnet',
      rpcUrls: ['https://pacific-rpc.manta.network/http'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Manta Explorer', url: 'https://pacific-explorer.manta.network' }],
    website: 'https://manta.network',
    coingeckoId: 'manta-network',
    isActive: true,
  }),

  createEVMChain({
    id: 'blast',
    name: 'Blast',
    symbol: 'ETH',
    aliases: ['blast-mainnet'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#FCFC03',
    icon: '💥',
    chainId: 81457,
    mainnet: {
      name: 'Blast Mainnet',
      rpcUrls: ['https://rpc.blast.io'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'BlastScan', url: 'https://blastscan.io' }],
    website: 'https://blast.io',
    coingeckoId: 'ethereum',
    isActive: true,
  }),

  createEVMChain({
    id: 'mode',
    name: 'Mode',
    symbol: 'ETH',
    aliases: ['mode-mainnet'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#DFFE00',
    icon: '🟡',
    chainId: 34443,
    mainnet: {
      name: 'Mode Mainnet',
      rpcUrls: ['https://mainnet.mode.network'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Mode Explorer', url: 'https://explorer.mode.network' }],
    website: 'https://mode.network',
    coingeckoId: 'mode',
    isActive: true,
  }),

  createEVMChain({
    id: 'fraxtal',
    name: 'Fraxtal',
    symbol: 'frxETH',
    aliases: ['fraxtal-mainnet'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#000000',
    icon: '⚫',
    chainId: 252,
    mainnet: {
      name: 'Fraxtal Mainnet',
      rpcUrls: ['https://rpc.frax.com'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Fraxscan', url: 'https://fraxscan.com' }],
    website: 'https://frax.com',
    coingeckoId: 'frax-share',
    isActive: true,
  }),

  createEVMChain({
    id: 'kroma',
    name: 'Kroma',
    symbol: 'ETH',
    aliases: ['kroma-mainnet'],
    category: 'layer2',
    consensus: 'zk',
    color: '#79FF79',
    icon: '🟢',
    chainId: 255,
    mainnet: {
      name: 'Kroma Mainnet',
      rpcUrls: ['https://api.kroma.network'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Kroma Explorer', url: 'https://blockscout.kroma.network' }],
    website: 'https://kroma.network',
    coingeckoId: 'kroma',
    isActive: true,
  }),

  // ============================================================
  // GAMING & METAVERSE EVMs
  // ============================================================
  createEVMChain({
    id: 'ronin',
    name: 'Ronin',
    symbol: 'RON',
    aliases: ['ronin-mainnet', 'axie'],
    category: 'gaming',
    consensus: 'pos',
    color: '#1273EA',
    icon: '⚔️',
    chainId: 2020,
    mainnet: {
      name: 'Ronin Mainnet',
      rpcUrls: ['https://api.roninchain.com/rpc'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Ronin Explorer', url: 'https://explorer.roninchain.com' }],
    website: 'https://roninchain.com',
    coingeckoId: 'ronin',
    isActive: true,
  }),

  createEVMChain({
    id: 'immutable-x',
    name: 'Immutable zkEVM',
    symbol: 'IMX',
    aliases: ['immutable', 'imx'],
    category: 'gaming',
    consensus: 'zk',
    color: '#00C3FF',
    icon: '🎮',
    chainId: 13371,
    mainnet: {
      name: 'Immutable zkEVM Mainnet',
      rpcUrls: ['https://rpc.immutable.com'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Immutable Explorer', url: 'https://explorer.immutable.com' }],
    website: 'https://immutable.com',
    coingeckoId: 'immutable-x',
    isActive: true,
  }),

  createEVMChain({
    id: 'beam',
    name: 'Beam',
    symbol: 'BEAM',
    aliases: ['beam-mainnet', 'merit-circle'],
    category: 'gaming',
    consensus: 'pos',
    color: '#FF5500',
    icon: '🎯',
    chainId: 4337,
    mainnet: {
      name: 'Beam Mainnet',
      rpcUrls: ['https://build.onbeam.com/rpc'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Beam Explorer', url: 'https://subnets.avax.network/beam' }],
    website: 'https://onbeam.com',
    coingeckoId: 'beam-2',
    isActive: true,
  }),

  createEVMChain({
    id: 'xai',
    name: 'Xai',
    symbol: 'XAI',
    aliases: ['xai-mainnet'],
    category: 'gaming',
    consensus: 'arbitrum',
    color: '#F30919',
    icon: '🎲',
    chainId: 660279,
    mainnet: {
      name: 'Xai Mainnet',
      rpcUrls: ['https://xai-chain.net/rpc'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Xai Explorer', url: 'https://explorer.xai-chain.net' }],
    website: 'https://xai.games',
    coingeckoId: 'xai-blockchain',
    isActive: true,
  }),

  // ============================================================
  // DEFI FOCUSED EVMs
  // ============================================================
  createEVMChain({
    id: 'kava',
    name: 'Kava',
    symbol: 'KAVA',
    aliases: ['kava-mainnet'],
    category: 'defi',
    consensus: 'pos',
    color: '#FF564F',
    icon: '🔴',
    chainId: 2222,
    mainnet: {
      name: 'Kava EVM',
      rpcUrls: ['https://evm.kava.io'],
      defaultPorts: { rpc: 8545, p2p: 26656, ws: 8546 },
    },
    explorers: [{ name: 'Kava Explorer', url: 'https://explorer.kava.io' }],
    website: 'https://kava.io',
    coingeckoId: 'kava',
    isActive: true,
  }),

  createEVMChain({
    id: 'metis',
    name: 'Metis Andromeda',
    symbol: 'METIS',
    aliases: ['metis', 'metis-andromeda'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#00D2FF',
    icon: '🌌',
    chainId: 1088,
    mainnet: {
      name: 'Metis Andromeda',
      rpcUrls: ['https://andromeda.metis.io/?owner=1088'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Metis Explorer', url: 'https://andromeda-explorer.metis.io' }],
    website: 'https://metis.io',
    coingeckoId: 'metis-token',
    isActive: true,
  }),

  createEVMChain({
    id: 'aurora',
    name: 'Aurora',
    symbol: 'ETH',
    aliases: ['aurora-mainnet', 'near-aurora'],
    category: 'layer2',
    consensus: 'pos',
    color: '#70D44B',
    icon: '🌅',
    chainId: 1313161554,
    mainnet: {
      name: 'Aurora Mainnet',
      rpcUrls: ['https://mainnet.aurora.dev'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Aurora Explorer', url: 'https://explorer.aurora.dev' }],
    website: 'https://aurora.dev',
    coingeckoId: 'aurora-near',
    isActive: true,
  }),

  createEVMChain({
    id: 'celo',
    name: 'Celo',
    symbol: 'CELO',
    aliases: ['celo-mainnet'],
    category: 'layer1',
    consensus: 'pos',
    color: '#35D07F',
    icon: '🌿',
    chainId: 42220,
    mainnet: {
      name: 'Celo Mainnet',
      rpcUrls: ['https://forno.celo.org'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Celo Explorer', url: 'https://explorer.celo.org' }],
    website: 'https://celo.org',
    coingeckoId: 'celo',
    isActive: true,
  }),

  createEVMChain({
    id: 'moonbeam',
    name: 'Moonbeam',
    symbol: 'GLMR',
    aliases: ['moonbeam-mainnet', 'polkadot-evm'],
    category: 'layer1',
    consensus: 'pos',
    color: '#53CBC9',
    icon: '🌙',
    chainId: 1284,
    mainnet: {
      name: 'Moonbeam',
      rpcUrls: ['https://rpc.api.moonbeam.network'],
      defaultPorts: { rpc: 9944, p2p: 30333, ws: 9945 },
    },
    explorers: [{ name: 'Moonscan', url: 'https://moonbeam.moonscan.io' }],
    website: 'https://moonbeam.network',
    coingeckoId: 'moonbeam',
    isActive: true,
  }),

  createEVMChain({
    id: 'moonriver',
    name: 'Moonriver',
    symbol: 'MOVR',
    aliases: ['moonriver-mainnet', 'kusama-evm'],
    category: 'layer1',
    consensus: 'pos',
    color: '#F2B705',
    icon: '🌊',
    chainId: 1285,
    mainnet: {
      name: 'Moonriver',
      rpcUrls: ['https://rpc.api.moonriver.moonbeam.network'],
      defaultPorts: { rpc: 9944, p2p: 30333, ws: 9945 },
    },
    explorers: [{ name: 'Moonscan', url: 'https://moonriver.moonscan.io' }],
    website: 'https://moonbeam.network/networks/moonriver',
    coingeckoId: 'moonriver',
    isActive: true,
  }),

  createEVMChain({
    id: 'harmony',
    name: 'Harmony',
    symbol: 'ONE',
    aliases: ['harmony-mainnet'],
    category: 'layer1',
    consensus: 'pos',
    color: '#00ADE8',
    icon: '🎵',
    chainId: 1666600000,
    mainnet: {
      name: 'Harmony Mainnet',
      rpcUrls: ['https://api.harmony.one'],
      defaultPorts: { rpc: 9500, p2p: 9000, ws: 9800 },
    },
    explorers: [{ name: 'Harmony Explorer', url: 'https://explorer.harmony.one' }],
    website: 'https://harmony.one',
    coingeckoId: 'harmony',
    isActive: true,
  }),

  createEVMChain({
    id: 'klaytn',
    name: 'Klaytn',
    symbol: 'KLAY',
    aliases: ['klaytn-mainnet', 'kaia'],
    category: 'layer1',
    consensus: 'pbft',
    color: '#FF6600',
    icon: '🔶',
    chainId: 8217,
    mainnet: {
      name: 'Klaytn Mainnet',
      rpcUrls: ['https://public-node-api.klaytnapi.com/v1/cypress'],
      defaultPorts: { rpc: 8551, p2p: 32323, ws: 8552 },
    },
    explorers: [{ name: 'Klaytn Scope', url: 'https://scope.klaytn.com' }],
    website: 'https://klaytn.foundation',
    coingeckoId: 'klay-token',
    isActive: true,
  }),

  createEVMChain({
    id: 'oasys',
    name: 'Oasys',
    symbol: 'OAS',
    aliases: ['oasys-mainnet'],
    category: 'gaming',
    consensus: 'pos',
    color: '#00D4AA',
    icon: '🎮',
    chainId: 248,
    mainnet: {
      name: 'Oasys Mainnet',
      rpcUrls: ['https://rpc.mainnet.oasys.games'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Oasys Explorer', url: 'https://explorer.oasys.games' }],
    website: 'https://oasys.games',
    coingeckoId: 'oasys',
    isActive: true,
  }),

  createEVMChain({
    id: 'boba',
    name: 'Boba Network',
    symbol: 'BOBA',
    aliases: ['boba-mainnet'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#CCFF00',
    icon: '🧋',
    chainId: 288,
    mainnet: {
      name: 'Boba Mainnet',
      rpcUrls: ['https://mainnet.boba.network'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Boba Explorer', url: 'https://bobascan.com' }],
    website: 'https://boba.network',
    coingeckoId: 'boba-network',
    isActive: true,
  }),

  createEVMChain({
    id: 'evmos',
    name: 'Evmos',
    symbol: 'EVMOS',
    aliases: ['evmos-mainnet', 'cosmos-evm'],
    category: 'layer1',
    consensus: 'pos',
    color: '#ED4E33',
    icon: '⚛️',
    chainId: 9001,
    mainnet: {
      name: 'Evmos Mainnet',
      rpcUrls: ['https://evmos-evm.publicnode.com'],
      defaultPorts: { rpc: 8545, p2p: 26656, ws: 8546 },
    },
    explorers: [{ name: 'Evmos Explorer', url: 'https://escan.live' }],
    website: 'https://evmos.org',
    coingeckoId: 'evmos',
    isActive: true,
  }),

  createEVMChain({
    id: 'fuse',
    name: 'Fuse',
    symbol: 'FUSE',
    aliases: ['fuse-mainnet'],
    category: 'layer1',
    consensus: 'pos',
    color: '#B4F9BA',
    icon: '⚡',
    chainId: 122,
    mainnet: {
      name: 'Fuse Mainnet',
      rpcUrls: ['https://rpc.fuse.io'],
      defaultPorts: { rpc: 8545, p2p: 30300, ws: 8546 },
    },
    explorers: [{ name: 'Fuse Explorer', url: 'https://explorer.fuse.io' }],
    website: 'https://fuse.io',
    coingeckoId: 'fuse-network-token',
    isActive: true,
  }),

  createEVMChain({
    id: 'iotex',
    name: 'IoTeX',
    symbol: 'IOTX',
    aliases: ['iotex-mainnet'],
    category: 'infrastructure',
    consensus: 'pos',
    color: '#00D4D5',
    icon: '📡',
    chainId: 4689,
    mainnet: {
      name: 'IoTeX Mainnet',
      rpcUrls: ['https://babel-api.mainnet.iotex.io'],
      defaultPorts: { rpc: 8545, p2p: 4689, ws: 8546 },
    },
    explorers: [{ name: 'IoTeX Scan', url: 'https://iotexscan.io' }],
    website: 'https://iotex.io',
    coingeckoId: 'iotex',
    isActive: true,
  }),

  createEVMChain({
    id: 'theta',
    name: 'Theta Network',
    symbol: 'THETA',
    aliases: ['theta-mainnet'],
    category: 'infrastructure',
    consensus: 'pos',
    color: '#2AB8E6',
    icon: 'θ',
    chainId: 361,
    mainnet: {
      name: 'Theta Mainnet',
      rpcUrls: ['https://eth-rpc-api.thetatoken.org/rpc'],
      defaultPorts: { rpc: 8545, p2p: 5000, ws: 8546 },
    },
    explorers: [{ name: 'Theta Explorer', url: 'https://explorer.thetatoken.org' }],
    website: 'https://thetatoken.org',
    coingeckoId: 'theta-token',
    isActive: true,
  }),

  createEVMChain({
    id: 'okx',
    name: 'OKX Chain',
    symbol: 'OKT',
    aliases: ['okc', 'okexchain'],
    category: 'exchange',
    consensus: 'pos',
    color: '#000000',
    icon: '⬛',
    chainId: 66,
    mainnet: {
      name: 'OKX Chain Mainnet',
      rpcUrls: ['https://exchainrpc.okex.org'],
      defaultPorts: { rpc: 8545, p2p: 26656, ws: 8546 },
    },
    explorers: [{ name: 'OKLink', url: 'https://www.oklink.com/oktc' }],
    website: 'https://okx.com/oktc',
    coingeckoId: 'oec-token',
    isActive: true,
  }),

  createEVMChain({
    id: 'core',
    name: 'Core',
    symbol: 'CORE',
    aliases: ['core-mainnet', 'satoshi-plus'],
    category: 'layer1',
    consensus: 'satoshi-plus',
    color: '#FF9211',
    icon: '🟠',
    chainId: 1116,
    mainnet: {
      name: 'Core Mainnet',
      rpcUrls: ['https://rpc.coredao.org'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Core Scan', url: 'https://scan.coredao.org' }],
    website: 'https://coredao.org',
    coingeckoId: 'coredaoorg',
    isActive: true,
  }),

  createEVMChain({
    id: 'pulsechain',
    name: 'PulseChain',
    symbol: 'PLS',
    aliases: ['pulse', 'pulsechain-mainnet'],
    category: 'layer1',
    consensus: 'pos',
    color: '#00FF9D',
    icon: '💚',
    chainId: 369,
    mainnet: {
      name: 'PulseChain Mainnet',
      rpcUrls: ['https://rpc.pulsechain.com'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'PulseScan', url: 'https://scan.pulsechain.com' }],
    website: 'https://pulsechain.com',
    coingeckoId: 'pulsechain',
    isActive: true,
  }),

  createEVMChain({
    id: 'flare',
    name: 'Flare',
    symbol: 'FLR',
    aliases: ['flare-mainnet'],
    category: 'layer1',
    consensus: 'fba',
    color: '#E62058',
    icon: '🔥',
    chainId: 14,
    mainnet: {
      name: 'Flare Mainnet',
      rpcUrls: ['https://flare-api.flare.network/ext/C/rpc'],
      defaultPorts: { rpc: 9650, p2p: 9651, ws: 9652 },
    },
    explorers: [{ name: 'Flare Explorer', url: 'https://flare-explorer.flare.network' }],
    website: 'https://flare.network',
    coingeckoId: 'flare-networks',
    isActive: true,
  }),

  createEVMChain({
    id: 'songbird',
    name: 'Songbird',
    symbol: 'SGB',
    aliases: ['songbird-mainnet', 'flare-canary'],
    category: 'layer1',
    consensus: 'fba',
    color: '#00B4FF',
    icon: '🐦',
    chainId: 19,
    mainnet: {
      name: 'Songbird Mainnet',
      rpcUrls: ['https://songbird-api.flare.network/ext/C/rpc'],
      defaultPorts: { rpc: 9650, p2p: 9651, ws: 9652 },
    },
    explorers: [{ name: 'Songbird Explorer', url: 'https://songbird-explorer.flare.network' }],
    website: 'https://flare.network/songbird',
    coingeckoId: 'songbird',
    isActive: true,
  }),

  createEVMChain({
    id: 'zkfair',
    name: 'ZKFair',
    symbol: 'USDC',
    aliases: ['zkfair-mainnet'],
    category: 'layer2',
    consensus: 'zk',
    color: '#1D4ED8',
    icon: '⚖️',
    chainId: 42766,
    mainnet: {
      name: 'ZKFair Mainnet',
      rpcUrls: ['https://rpc.zkfair.io'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'ZKFair Explorer', url: 'https://scan.zkfair.io' }],
    website: 'https://zkfair.io',
    coingeckoId: 'zkfair',
    isActive: true,
  }),

  createEVMChain({
    id: 'polygon-zkevm',
    name: 'Polygon zkEVM',
    symbol: 'ETH',
    aliases: ['polygon-zkevm-mainnet', 'zkevm'],
    category: 'layer2',
    consensus: 'zk',
    color: '#7B3FE4',
    icon: '🔷',
    chainId: 1101,
    mainnet: {
      name: 'Polygon zkEVM Mainnet',
      rpcUrls: ['https://zkevm-rpc.com'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Polygon zkEVM Explorer', url: 'https://zkevm.polygonscan.com' }],
    website: 'https://polygon.technology/polygon-zkevm',
    coingeckoId: 'ethereum',
    isActive: true,
  }),

  createEVMChain({
    id: 'opbnb',
    name: 'opBNB',
    symbol: 'BNB',
    aliases: ['opbnb-mainnet', 'bnb-l2'],
    category: 'layer2',
    consensus: 'optimistic',
    color: '#F0B90B',
    icon: '🔸',
    chainId: 204,
    mainnet: {
      name: 'opBNB Mainnet',
      rpcUrls: ['https://opbnb-mainnet-rpc.bnbchain.org'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'opBNB Scan', url: 'https://opbnbscan.com' }],
    website: 'https://opbnb.bnbchain.org',
    coingeckoId: 'binancecoin',
    isActive: true,
  }),

  createEVMChain({
    id: 'wemix',
    name: 'WEMIX3.0',
    symbol: 'WEMIX',
    aliases: ['wemix-mainnet'],
    category: 'gaming',
    consensus: 'spos',
    color: '#12B886',
    icon: '🟩',
    chainId: 1111,
    mainnet: {
      name: 'WEMIX3.0 Mainnet',
      rpcUrls: ['https://api.wemix.com'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'WEMIX Scan', url: 'https://explorer.wemix.com' }],
    website: 'https://wemix.com',
    coingeckoId: 'wemix-token',
    isActive: true,
  }),

  createEVMChain({
    id: 'taiko',
    name: 'Taiko',
    symbol: 'ETH',
    aliases: ['taiko-mainnet'],
    category: 'layer2',
    consensus: 'zk',
    color: '#E81899',
    icon: '🥁',
    chainId: 167000,
    mainnet: {
      name: 'Taiko Mainnet',
      rpcUrls: ['https://rpc.mainnet.taiko.xyz'],
      defaultPorts: { rpc: 8545, p2p: 30303, ws: 8546 },
    },
    explorers: [{ name: 'Taiko Explorer', url: 'https://taikoscan.io' }],
    website: 'https://taiko.xyz',
    coingeckoId: 'taiko',
    isActive: true,
  }),

  createEVMChain({
    id: 'sei',
    name: 'Sei',
    symbol: 'SEI',
    aliases: ['sei-mainnet', 'sei-evm'],
    category: 'layer1',
    consensus: 'pos',
    color: '#9B1C1C',
    icon: '🌊',
    chainId: 1329,
    mainnet: {
      name: 'Sei Mainnet',
      rpcUrls: ['https://evm-rpc.sei-apis.com'],
      defaultPorts: { rpc: 8545, p2p: 26656, ws: 8546 },
    },
    explorers: [{ name: 'Sei Scan', url: 'https://seitrace.com' }],
    website: 'https://sei.io',
    coingeckoId: 'sei-network',
    isActive: true,
  }),
];
