/**
 * ============================================================
 * GAMING CHAINS - Gaming & Metaverse tokens
 * ============================================================
 */

import { BlockchainDefinition, createEVMChain } from '../types';

export const GAMING_CHAINS: BlockchainDefinition[] = [
  createEVMChain({ id: 'axie-infinity', name: 'Axie Infinity', symbol: 'AXS', category: 'gaming', consensus: 'other', color: '#0055D5', chainId: 2020, mainnet: { name: 'Ronin', rpcUrls: ['https://api.roninchain.com/rpc'] }, website: 'https://axieinfinity.com', coingeckoId: 'axie-infinity', isActive: true, features: { gaming: true, nft: true } }),
  createEVMChain({ id: 'sandbox', name: 'The Sandbox', symbol: 'SAND', category: 'gaming', consensus: 'other', color: '#00ADEF', chainId: 1, mainnet: { name: 'SAND (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://sandbox.game', coingeckoId: 'the-sandbox', isActive: true, features: { gaming: true, nft: true } }),
  createEVMChain({ id: 'decentraland', name: 'Decentraland', symbol: 'MANA', category: 'gaming', consensus: 'other', color: '#FF2D55', chainId: 1, mainnet: { name: 'MANA (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://decentraland.org', coingeckoId: 'decentraland', isActive: true, features: { gaming: true, nft: true } }),
  createEVMChain({ id: 'gala', name: 'Gala', symbol: 'GALA', category: 'gaming', consensus: 'other', color: '#1D1D1D', chainId: 1, mainnet: { name: 'GALA (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://gala.com', coingeckoId: 'gala', isActive: true, features: { gaming: true, nft: true } }),
  createEVMChain({ id: 'enjin', name: 'Enjin Coin', symbol: 'ENJ', category: 'gaming', consensus: 'other', color: '#624DBF', chainId: 1, mainnet: { name: 'ENJ (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://enjin.io', coingeckoId: 'enjincoin', isActive: true, features: { gaming: true, nft: true } }),
  createEVMChain({ id: 'illuvium', name: 'Illuvium', symbol: 'ILV', category: 'gaming', consensus: 'other', color: '#7B3FE4', chainId: 1, mainnet: { name: 'ILV (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://illuvium.io', coingeckoId: 'illuvium', isActive: true, features: { gaming: true, defi: true } }),
  createEVMChain({ id: 'beam', name: 'Beam', symbol: 'BEAM', category: 'gaming', consensus: 'pos', color: '#FF5E00', chainId: 4337, mainnet: { name: 'Beam Network', rpcUrls: ['https://build.onbeam.com/rpc'] }, website: 'https://onbeam.com', coingeckoId: 'beam-2', isActive: true, features: { gaming: true, nft: true, smartContracts: true } }),
  createEVMChain({ id: 'ronin', name: 'Ronin', symbol: 'RON', category: 'gaming', consensus: 'pos', color: '#1273EA', chainId: 2020, mainnet: { name: 'Ronin', rpcUrls: ['https://api.roninchain.com/rpc'] }, website: 'https://roninchain.com', coingeckoId: 'ronin', isActive: true, features: { gaming: true, smartContracts: true } }),
  createEVMChain({ id: 'magic', name: 'Magic', symbol: 'MAGIC', category: 'gaming', consensus: 'other', color: '#DC143C', chainId: 42161, mainnet: { name: 'MAGIC (Arbitrum)', rpcUrls: ['https://arb1.arbitrum.io/rpc'] }, website: 'https://treasure.lol', coingeckoId: 'magic', isActive: true, features: { gaming: true, nft: true } }),
  createEVMChain({ id: 'wax', name: 'WAX', symbol: 'WAXP', category: 'gaming', consensus: 'dpos', color: '#FF8500', chainId: 1, mainnet: { name: 'WAX (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://wax.io', coingeckoId: 'wax', isActive: true, features: { gaming: true, nft: true } }),
  createEVMChain({ id: 'ultra', name: 'Ultra', symbol: 'UOS', category: 'gaming', consensus: 'other', color: '#8B00FF', chainId: 1, mainnet: { name: 'UOS (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://ultra.io', coingeckoId: 'ultra', isActive: true, features: { gaming: true } }),
  createEVMChain({ id: 'ape', name: 'ApeCoin', symbol: 'APE', category: 'gaming', consensus: 'other', color: '#0047FF', chainId: 1, mainnet: { name: 'APE (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://apecoin.com', coingeckoId: 'apecoin', isActive: true, features: { gaming: true, governance: true } }),
  createEVMChain({ id: 'pixels', name: 'Pixels', symbol: 'PIXEL', category: 'gaming', consensus: 'other', color: '#F5A623', chainId: 1, mainnet: { name: 'PIXEL (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://pixels.xyz', coingeckoId: 'pixels', isActive: true, features: { gaming: true } }),
  createEVMChain({ id: 'portal', name: 'Portal', symbol: 'PORTAL', category: 'gaming', consensus: 'other', color: '#7B68EE', chainId: 1, mainnet: { name: 'PORTAL (Ethereum)', rpcUrls: ['https://eth.llamarpc.com'] }, website: 'https://portalgaming.com', coingeckoId: 'portal-2', isActive: true, features: { gaming: true, crossChain: true } }),
  createEVMChain({ id: 'xai', name: 'Xai', symbol: 'XAI', category: 'gaming', consensus: 'pos', color: '#F50057', chainId: 660279, mainnet: { name: 'Xai', rpcUrls: ['https://xai-chain.net/rpc'] }, website: 'https://xai.games', coingeckoId: 'xai-blockchain', isActive: true, features: { gaming: true, smartContracts: true } }),
];
